name: Build and Deploy Android APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.x'

    - name: Install dependencies
      run: flutter pub get

    - name: Build APK
      run: flutter build apk --release

    - name: Install Azure CLI
      run: curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

    - name: Upload to Azure Blob Storage
      env:
        AZURE_STORAGE_SAS_TOKEN: ${{ secrets.AZURE_STORAGE_SAS_TOKEN }}
      run: |
        ACCOUNT_NAME="azuprddatasave"
        CONTAINER_NAME="cars-flutter"
        FILE_PATH="build/app/outputs/flutter-apk/app-release.apk"
        BLOB_NAME="car_puzzle_app_$(date +%Y%m%d_%H%M%S).apk"
        az storage blob upload \
          --account-name $ACCOUNT_NAME \
          --container-name $CONTAINER_NAME \
          --name $BLOB_NAME \
          --file $FILE_PATH \
          --sas-token "$AZURE_STORAGE_SAS_TOKEN"
        BLOB_URL="https://$ACCOUNT_NAME.blob.core.windows.net/$CONTAINER_NAME/$BLOB_NAME"
        echo "APK_URL=$BLOB_URL" >> $GITHUB_ENV

    - name: Display APK URL
      env:
        APK_URL: ${{ env.APK_URL }}
      run: echo "APK uploaded to: $APK_URL"
